export const URLS = {
  HOME: "/",
  LOGIN: "/signin",
  REGISTER: "/register",

  SUBSCRIPTION: "",
  ADD_SUBSCRIPTION: "",
  ADD_FEE: "",
  ADD_CATEGORY: "",
  CATEGORIES: "",
  TAXES: "",
  SUB_CATEGORY: "",
  ADD_BRAND: "",
  BRAND: "",
  PAYMENT_BUYER: "",
  PAYMENT_SELLER: "",
  PAYMENT_INVOICE: "",
  BUYER_PROFILE: "",
  BUYER_BOOKING: "",
  BUYER_INVOICE: "",
  ORDERS_VIEW_BUYER: "",
  ORDERS_VIEW_SELLER: "",
  ORDERS_VIEW_INVOICE: "",
  PAYMENT_PLANS_INVOICE: "",
  POST_ADS_USER_PROFILE: "",
  SELLER_PROFILE: "",
  SELLER_PRODUCTS: "",
  SELLER_BOOKING: "",
  SELLER_INVOICE: "",
  SELLER: "",
  BUYER: "",
  POST_ADS: "",
  ORDERS: "",
  PAYOUT_REQUESTS: "",
  PAYMENT_ORDERS: "",
  PAYMENT_PLANS: "",
  SELLER_PRODUCTS_VIEW: "",

  FORGET_PASSWORD: "/forget-password",
  RESET_PASSWORD: "/reset-password",
  CART: "/cart",
  CHECKOUT: "/checkout",

  PRODUCT: (id: string) => `/product/${id}`,
  NOTIFICATION: "/notification",
  BUYER_ACCOUNT_ORDERS: "/buyer-account/orders",
  BUYER_ACCOUNT_INVOICE: "/buyer-account/invoice",
  BUYER_ACCOUNT_ANALYTICS: "/buyer-account/analytics",
  PROFILE: "/profile",
  CHANGE_PASSWORD: "/change-password",
  DOCUMENT: "/document",

  SELLER_ACCOUNT_LISTING: "/seller-account/listing",
  SELLER_ACCOUNT_ANALYTICS: "/seller-account/analytics",
  SELLER_ACCOUNT_ORDERS: "/seller-account/order",
  SELLER_ACCOUNT_MESSAGES: "/seller-account/messages",
  SELLER_ACCOUNT_INVOICE: "/seller-account/invoice",
  SELLER_ACCOUNT_MEMBERSHIP: "/seller-account/membership",

  PAYMENTS: "/payments/get-paid",
  PAYMENTS_BILLING: "/payments/billing",
  ADD_BANK_CARD: "/payments/get-paid/add-bank",
  ADD_BILLING_BANK_CARD: "/payments/billing/add-bank",

  NOTIFICATION_SETTING: "/notification-setting",

  POST_AD: "/post-ad",
  POST_NEW_AD: "/post-new-ad",
  VERIFY_OTP: "/verify-otp",
  CATEGORY: "/category",
  EDIT_ADD: (id: string) => `/post-new-ad?add_id=${id}`,
  PAYOUT_ITEMS_SELLER: "/payments/payout-items/seller",
  PAYOUT_ITEMS_BUYER: "/payments/payout-items/buyer",
  PAYOUT_ITEMS_HISTORY: "/payments/payout-items/history",
  PREVIEW_PRODUCT: "/product/preview"
};
